Temporary deactive container naming
Reason: we get failures like:
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.43/containers/create?name=test-ubuntu-22.04-master-latest-b6b8a449a9-20240112090448:
Conflict ("Conflict. The container name "/test-ubuntu-22.04-master-latest-b6b8a449a9-20240112090448" is already in use by container "xyz". You have to remove (or rename) that container to be able to reuse that name.")

Change-Id: I9497571e2bb720fb12767fcdf58ac6b82a29f6ce