Revert "view.py: intercept queries and add link to GUI"
It somehow fixes one of my local problems

AttributeError: module 'cmk.gui.plugins.wato' has no attribute 'utils'

I don't see the connection

This reverts commit 9557627705d26794f74512e276ec5a7423b00c55.