omd: fix OSError on aborting update
If the update from 2.3.0 to 2.4.0 is aborted, the following error was
raised:
```
    os.rmdir(self)
OSError: [Errno 39] Directory not empty: '/omd/sites/v230p22/etc/rabbitmq/conf.d'
```
This was because the rabbitmq hook modified a file, but did not declare
this in the rollback mechanism.

CMK-20230

Change-Id: I1ab80d174efacd35ebfed2ec3676b7144ae6fd51