cmk-migrate-http: Fix `ValueError`
`gui_context` requires this import. It is unclear when and where this
changed.

```
  File "/omd/sites/v250/lib/python3/cmk/gui/wsgi/app.py", line 46, in make_wsgi_app
    raise ValueError(f"Invalid edition: {edition}")
ValueError: Invalid edition: Edition.PRO
```

CMK-27780

Change-Id: Ie4c011ece0528bc89bb7566576043892aa8030ea