Remove bson dev dependency
This dependency is conflicting with pymongo and resulting in the
following exception:

----
ImportError while importing test module '/var/lib/jenkins/workspace/cmk_master/unit_tests/check_mk/tests/unit/agents/plugins/test_mk_mongodb.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/_pytest/python.py:507: in _importtestmodule
    mod = self.fspath.pyimport(ensuresyspath=importmode)
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/py/_path/local.py:701: in pyimport
    __import__(modname)
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py:304: in load_module
    exec(co, mod.__dict__)
unit/agents/plugins/test_mk_mongodb.py:5: in <module>
    from bson.json_util import loads
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/bson/json_util.py:116: in <module>
    from pymongo.errors import ConfigurationError
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/pymongo/__init__.py:77: in <module>
    from pymongo.collection import ReturnDocument
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/pymongo/collection.py:20: in <module>
    from bson.code import Code
../virtual-envs/2.7/.venv/local/lib/python2.7/site-packages/bson/code.py:18: in <module>
    from bson.py3compat import abc, string_type, PY3, text_type
E   ImportError: cannot import name abc
---

According to https://github.com/py-bson/bson/issues/82 both
packages are conflicting and bson needs to be cleaned up.

Change-Id: I82383157176ba3230408285c142d7fc92cedccae