omd: fix backup_managed
To determine which files are modified by the update, it is checked which
paths existed in the skel hierarchy, both before and after the update.
This mechanism did not work correctly for symlinks. This caused the
following crash:

```
  File "/omd/versions/2.4.0-2024.07.24.cee/lib/python3/omdlib/update.py", line 31, in store
    destination.symlink_to(source.readlink())
  File "/omd/versions/2.4.0-2024.07.24.cee/lib/python3.12/pathlib.py", line 1386, in symlink_to
    os.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: 'lib/omd/bash_completion' -> '/omd/sites/heute/.update_backup/etc/bash_completion.d/bash_completion'
```

Change-Id: Ie45872a7bb9ca8cf9effe15f1d73a1afcbf6c943