Revert "Reland: esx_vsphere_datastores: migration I"
This reverts commit ada546d68bd16464ae681cdc916f5cac81649cd5.

Reason for revert: breaks update tests with:
```
                err_msg = (
                    f"In the {hostname} host the following services were not expected to be missing "
                    f"{missed_services[hostname]}"
                )
>               assert not missed_services[hostname], err_msg
E               AssertionError: In the vcenter.company.com host the following services were not expected to be missing ['Filesystem IBM_EasyT_Datastore07', 'Filesystem Nimble-006', 'Filesystem Nimble-004', 'Filesystem IBM_EasyT_Datastore08', 'Filesystem datastore1 (1)', 'Filesystem IBM_EasyT_Datastore03', 'Filesystem IBM_EasyT_Datastore04', 'Filesystem IBM_EasyT_Datastore02', 'Filesystem IBM_EasyT_Datastore06', 'Filesystem IBM_EasyT_Datastore00', 'Filesystem Nimble-002', 'Filesystem Nimble-001', 'Filesystem Nimble-ISO', 'Filesystem Nimble-DB-02', 'Filesystem VeeamBackup_srv039', 'Filesystem IBM_EasyT_Datastore05', 'Filesystem IBM_EasyT_DatastoreISO', 'Filesystem Nimble-003', 'Filesystem Nimble-Citrix', 'Filesystem IBM_EasyT_Datastore01', 'Filesystem IBM_EasyT_CitrixDatastore03', 'Filesystem Nimble-005', 'Filesystem Nimble-007', 'Filesystem Nimble-DB-01', 'Filesystem VeeamBackup_srv039.company.com', 'Filesystem Nimble-Clearpass', 'Filesystem datastore1']
E               assert not ['Filesystem IBM_EasyT_Datastore07', 'Filesystem Nimble-006', 'Filesystem Nimble-004', 'Filesystem IBM_EasyT_Datastore08', 'Filesystem datastore1 (1)', 'Filesystem IBM_EasyT_Datastore03', ...]
```

Change-Id: I9bf3534e8272a796d815f6b4ce372f763bd989de