7177 FIX Fix background job warning "IOError: [Errno 9] Bad file descriptor"
When starting a background job an unproblematic error message like this could
occur in the output of the background job log:

<code>
sys.stdin.close()
IOError: [Errno 9] Bad file descriptor
</code>

This was caused by an unclean stdin/stdout/stderr handling during job startup
since commit cd6563801d1de1bdb89edc23788c17904f296aa1.

Change-Id: I09a652b2f2373cf332aa37b8b4a0b23a493e189b