Revert "16382 FIX Cleanup SNMP version and bulkwalk rulesets"
It breaks integration tests:
E           tests.testlib.utils.UtilCalledProcessError: Command 'sudo su -l int_test -c 'python3 /omd/sites/int_test/helper_get_snmp_table.py'' returned non-zero exit status 1 ('Traceback (most recent call last):\n  File "/omd/sites/int_test/helper_get_snmp_table.py", line 43, in <module>\n    config = SNMPHostConfig.deserialize(params[2])\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/omd/sites/int_test/lib/python3/cmk/snmplib/_typedefs.py", line 143, in deserialize\n    return cls(**serialized_)\n           ^^^^^^^^^^^^^^^^^^\nTypeError: SNMPHostConfig.__init__() got an unexpected keyword argument \'snmp_version\'\n').

This reverts commit 6219cc057211b9928cfacde29d89aa82b536a881.