Fix TypeError for missing IPMI creds
Missing credentials raise

  TypeError: 'NoneType' object has no attribute '__getitem__'

This patch turns this low level exception into a more user-friendly one.

CMK-4143

Change-Id: Ifd720de350dc80b40a79bb721f911cf1e62f1229