FIX Fixed exception when handling connections from event unix socket
This issue has been introduced in december of 2013. It made the event
console terminate with an exception with a message like
<tt>AttributeError: 'tuple' object has no attribute 'close'</tt>. This
has been fixed now.