Revert "Piggyback-Hub: use processes instead of threads"
It breaks site:
Traceback (most recent call last):
  File "/omd/sites/int_test/lib/python3/cmk/piggyback_hub/utils.py", line 57, in run
    with Connection(APP_NAME, self.omd_root) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/int_test/lib/python3.12/site-packages/cmk/messaging/_connection.py", line 255, in __init__
    make_connection_params(omd_root, "localhost", get_local_port())
  File "/omd/sites/int_test/lib/python3.12/site-packages/cmk/messaging/_config.py", line 150, in make_connection_params
    ssl_options=pika.SSLOptions(_make_ssl_context(omd_root)),
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/int_test/lib/python3.12/site-packages/cmk/messaging/_config.py", line 158, in _make_ssl_context
    context = ssl.create_default_context(cafile=cacert_file(omd_root))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/int_test/lib/python3.12/ssl.py", line 708, in create_default_context
    context.load_verify_locations(cafile, capath, cadata)
FileNotFoundError: [Errno 2] No such file or directory

This reverts commit 3cd858b135725a4446f20de7e1bdd6c794ffe74e.

Change-Id: I0fb9e98db626c748a840fd973ec76d814314fc0c