13120 FIX MTR agent plugin: Make usable with Python 3
Under Python 3, the MTR agent plugin crashed with:
<tt>AttributeError: 'str' object has no attribute 'decode'</tt>.
This has been fixed. Note that you need to update the agent on
affected hosts for this werk to come into effect.

Closes #390

Change-Id: I0ff5c8b021c2301210afb80878d47563a47262f0