Fix for use_system_openssl being included in package.
Caused errors like the following:

    AssertionError: Found unexpected global file: /opt/omd/versions/2.5.0-2025.11.24.pro/use_system_openssl
    in /home/jenkins/agent/workspace/checkmk/master/builders/sign-cmk-distro-package/checkout/check-mk-pro-2.5.0-2025.11.24-sles15sp7-38.x86_64.rpm

Was caused by a bug in pkg_files including it's srcs transitive dependencies.

Change-Id: I5ce757451975b4c65e27884c904e8f2fdfee2c0a