Revert "Removes [lib]xmlsec1[-openssl][-dev] from build images"
It seems this is needed for building lxml:

Collecting lxml==4.9.2
  Downloading https://devpi.lan.tribe29.com/root/pypi/%2Bf/245/5cfaeb7ac7033/lxml-4.9.2.tar.gz (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 76.1 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.9.2.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]

This reverts commit 60b1b849562125745252e18ca8def3e5558959a9.