Add debug logging to saving of user profiles
We have recently observed CI failures such as
```
error: Failed to create sync archive [1]: tar:
var/check_mk/web/agent_registrar/automation.secret:
file changed as we read it
```

These failures seem to be caused by some other process editing the profile files
of non-exisiting users (the `agent_registrar` user doesn't exist anymore when
the failure happens). The `save_users` function might be the call site causing
the issue. Since we are currently out of other ideas, we add some debug logging
to verify this assumption in case the failure re-occurs.

Change-Id: Ie42855a4e5aafaf7e6f791e65ca07ad646df8d41