This fixes a crash like this:
UnboundLocalError: local variable 'disk_read_bytes' referenced before assignment

Conflicts:
	ChangeLog
	checks/winperf_phydisk