rrdtool: Explicitly set gnu99 standard instead of iso
This removes the following warnings

```
10:09:16  external/rrdtool_native/src/rrd_list.c:93:5: error: call to undeclared function 'asprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
10:09:16     93 |                                 SANE_ASPRINTF2(out, "%s", out_rec);
10:09:16        |                                 ^
10:09:16  external/rrdtool_native/src/rrd_list.c:43:6: note: expanded from macro 'SANE_ASPRINTF2'
10:09:16     43 |         if (asprintf(&_dest_str, _format, __VA_ARGS__) == -1) {         \
10:09:16        |             ^
```

Change-Id: I96f25041158014a89a26120b24e804ec943a82ca