Fix ambiguous conditional expression
Do not rely on the implementation detail that libstdc++ implements pairs
as specialized tuples.

This fixes the following error with libc++
```
packages/livestatus/src/StringUtils.cc:49:16: error: conditional expression is ambiguous;
'std::pair<std::string, std::string>' (aka 'pair<basic_string<char>, basic_string<char>>')
can be converted to 'tuple<__unwrap_ref_decay_t<string>, __unwrap_ref_decay_t<string>>' (aka 'tuple<std::string, std::string>') and vice versa
   49 |                ? mk::nextField(composite_key)
      |                ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   50 |                : make_tuple(mk::rstrip(composite_key.substr(0, semicolon)),
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   51 |                             mk::rstrip(composite_key.substr(semicolon + 1)));
      |                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

CMK-21295

Change-Id: I96937d458263810f507042de5b730aa93c1ea954