#2856 FIX winperf_phydisk: Not discovering on clusters where disk perfcounters are missing
This fixes a crash like this:

UnboundLocalError: local variable 'disk_read_bytes' referenced before assignment