14145 FIX Crash: Performance Graph dashlet without service context
When creating a performance graph dashlet without the service context you would expect
the dashlet to use the available host metrics from the Host Check Command.

Since 2.1.0i1 this was no longer possible because the dashlet crashed with the error:

<b>Exception: AttributeError ('str' object has no attribute 'values')</b>

Now the dashlet works as intended again.

Change-Id: I47d9027276d6c34f0abe4becccbf5a2a186bc340