Revert "ssc: strip prefix for relay hosts"
This reverts commit 713e24bf9658cf31b84546546cee0fd34292a1c4.

Reason for revert: breaks gh actions with:
```
cmk/base/config.py:3645: error: Cannot find implementation or library stub for module named "cmk.relay_fetcher_trigger.trigger"
```

Change-Id: I9239f125cc98926df953713bf7695c8695bdc2dd