Quick hack to get our CI green again.
We still need to figure out what is going on related to kwargs here:

    self = <[AttributeError("'FakeConnection' object has no attribute 'db'") raised in repr()] FakeConnection object at 0x7f561d3485e0>, args = ()
    kwargs = {'db': 0, 'decode_responses': True, 'encoding': 'utf-8', 'password': None, ...}

        def __init__(self, *args, **kwargs):
            self._server = kwargs.pop('server')
    >       super().__init__(*args, **kwargs)
    E       TypeError: __init__() got an unexpected keyword argument 'path'

    ../.venv/lib/python3.8/site-packages/fakeredis/_server.py:2689: TypeError

Change-Id: I6f5ef3955b79b8644f9e1e8e9eb12e3f3abd438a