4384 FIX Fixed exception on start page when using Python < 2.5
Fixed exception "AttributeError ('tuple' object has no attribute 'scheme')" which was introduced
with werk 3970 (1.2.8p14) which could occur with Python versions older than 2.5.

Change-Id: Iaa555c3dea4c469e7fbc2040c27739569a9399b3