Add missing test dependency
... in order to make mypy happy, was failing with:
packages/cmk-crypto/tests/test_certificate.py:16: error: Library stubs not installed for "dateutil.relativedelta"  [import-untyped]
packages/cmk-crypto/tests/test_certificate.py:16: note: Hint: "python3 -m pip install types-python-dateutil"
packages/cmk-crypto/tests/test_certificate.py:16: note: (or run "mypy --install-types" to install all missing stub packages)
packages/cmk-crypto/tests/test_certificate.py:16: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports

Change-Id: I5ba685311098e6176087d74452ec90fe20240d3f