11713 FIX PySNMP: Opaque Handling
If your SNMP device used the type "Opaque" to send
floats the values were not formatted properly which
caused some crashes later.

The error occured if Checks tried to use these corrupted
values. Error patterns looked like this:

ValueError: could not convert string to float: '\x9fx\x04?B\x8f\\'

Now the Opaque value is formatted.

Change-Id: I60f888d6004231b87b7cc7472af3c0c4385f21c8