Upgrade pymssql to resolve compilation error.
Upgrade pymssql to include this change:

    https://github.com/pymssql/pymssql/pull/977

Resolves the following error:

    src/pymssql/_mssql.pyx:671:106: Unclosed string literal

This was a long standing bug in this package, but didn't cause
compilation problems with earlier versions of cython.

Change-Id: Ieccaddea62815f959aa9d4e15f45d2d231d248ea