Revert "Don't ship cpp-libs"
It breaks e.g. under jammy with:
Traceback (most recent call last):
  File "/omd/sites/heute/bin/cmk", line 51, in <module>
    from cmk.trace.export import exporter_from_config, init_span_processor
  File "/omd/sites/heute/lib/python3.12/site-packages/cmk/trace/export.py", line 8, in <module>
    from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import OTLPSpanExporter
  File "/omd/sites/heute/lib/python3.12/site-packages/opentelemetry/exporter/otlp/proto/grpc/trace_exporter/__init__.py", line 21, in <module>
    from grpc import ChannelCredentials, Compression
  File "/omd/sites/heute/lib/python3.12/site-packages/grpc/__init__.py", line 22, in <module>
    from grpc import _compression
  File "/omd/sites/heute/lib/python3.12/site-packages/grpc/_compression.py", line 20, in <module>
    from grpc._cython import cygrpc
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.32' not found (required by /omd/sites/heute/lib/python3.12/site-packages/grpc/_cython/cygrpc.cpython-312-x86_64-linux-gnu.so)

This reverts commit 6b9bb8baa7d0d4b60f4128d0029c54d74240649d.

Change-Id: I7a263b1f7628b7ea0ca2ab6a605b50150697ec7c