Elasticsearch special agent: Make SSL cert. verification config optional
This fixes

WARNING: Invalid rule configuration detected (Ruleset:
special_agents:elasticsearch, Title: Elasticsearch, Folder: ,
Rule nr: 1,
Exception: The entry SSL certificate verification is missing)

during cmk-update-config.

CMK-12091

Change-Id: I90d5cb6ec589aba2b21ff9e1bfe43f564c3a1057