revert deletion of host_address, host_name
Werk 16409 caused the following regression, if the node_exporter option was set:
```
line 895, in _extract_config_args
    {"host_address": config["host_address"], "host_name": config["host_name"]}
                     ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'host_address'
```
For now we just revert the relevent argument thingy.

CMK-16767

Change-Id: I02ff49b4142eca12df99f78e927c5b0347da6e8e