7177 FIX Fix background job warning "IOError: [Errno 9] Bad file descriptor"
When starting a background job an unproblematic error message like this could
occur in the output of the background job log:

<code>
sys.stdin.close()
IOError: [Errno 9] Bad file descriptor
</code>

This was caused by an unclean stdin/stdout/stderr handling during job startup
since commit d6381e639416c760a2c72203a1255287a5842555.

Change-Id: I09a652b2f2373cf332aa37b8b4a0b23a493e189b