Make windows integration tests independent of top level pytest config
This is a package specific test job which is not executed in our Checkmk
python version nor regular virtual environment. Therefore we need to
separate both to prevent side effects.

As a follow-up this should be cleaned up. The test job should be using
some git controlled venv at least which it currently does not seem to
do according to the winagt-build-modules job output:

```
(...)
Downloading python-3.12.1_9585aacecd8_30.cab from cache...
The file exists in cache. Moving cached file to artifact
        1 file(s) moved.
[+] Downloaded successfully
Builds are successfull
make[1]: Entering directory 'd:/workdir/workspace/checkmk/master/cv/winagt-build-modules/checkout/agents/modules/windows/tests'
Integration tests starting
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\_pytest\config\__init__.py", line 746, in import_plugin
    __import__(importspec)
ModuleNotFoundError: No module named ' no:faker'
(...)
```

The pyproject.toml should probably be placed in a higher level and
component specific level directory.

Change-Id: I269870c626d9b5e969cafefbf46bdd4e6a7fec40