more strict typescript type checking
also fixing/ignoring the existing problems.

<template> in CmkFormList was removed, because vue-tsc complained:
    error TS6133: 'element_row' is declared but its value is never read.
theoretically this should be fixed with
https://github.com/vuejs/language-tools/commit/cb540323d4f0e80feed4feb4fea301f7d532f0c5
not sure why the fix does not apply to our problem.
but the template was not needed anyway, so i've worked around the issue.

Change-Id: Ie7070a6588bc2cd4e3b9ff952dee02b989f33698