17218 FIX diskspace: IndexError: string index out of range
If the `OMD_ROOT` was located on a filesystem, which started with a character
other than '/', then diskspace plugin would failwith the error:
```
File "/omd/sites/monitor/bin/diskspace", line 166, in _get_free_space
  if filesystem[0] == "/":
IndexError: string index out of range
```
This crash has been fixed. The call to `df -P -B1` was replaced with a direct
call to `os.statvfs`.

`df -P` calls `statfs` under the hood, which should correspond to
`statvfs` on other systems (typically `statvfs` is implemented on top of
`statfs`).

On my system, I have the following types of filesystems:
```
tmpfs                     tmpfs      1647972352      3305472   1644666880       1% /run
/dev/mapper/vgubuntu-root ext4     500609097728 330080231424 145024143360      70% /
tmpfs                     tmpfs      8239853568    172941312   8066912256       3% /dev/shm
tmpfs                     tmpfs         5242880        12288      5230592       1% /run/lock
efivarfs                  efivarfs       382876       268472       109284      72% /sys/firmware/efi/efivars
/dev/nvme0n1p2            ext4        737214464    111640576    571850752      17% /boot
tmpfs                     tmpfs      8239853568            0   8239853568       0% /run/qemu
/dev/nvme0n1p1            vfat        535805952     73936896    461869056      14% /boot/efi
tmpfs                     tmpfs      8239853568        57344   8239796224       1% /opt/omd/sites/new/tmp
tmpfs                     tmpfs      1647968256       110592   1647857664       1% /run/user/988
tmpfs                     tmpfs      1647968256       151552   1647816704       1% /run/user/1000
/dev/loop45               vfat          2076672            0      2076672       0% /tmp/new
/dev/loop46               ext2          2015232        24576      1888256       2% /tmp/fsmoutn
```

The loopback devices to give more coverage. For all these filesystems,
this implementation produced no change in output.

SUP-21679

Change-Id: I1c35f40e13e640de6b94184d219d1503dc31351e