11208 FIX check_mailboxes: Handle invalid mailbox names (CMK-5550)
A space character in a mailbox name provided via {--mailbox=<NAME>}, e.g. "My Inbox" would lead to a known exception:

imaplib.IMAP4.error: SELECT command error: BAD [b"parse error: wrong character; expected '(' but got 'I'"]

see https://bugs.python.org/issue13940

This fix quotes mailbox names and thus fixes the described behaviour.

Also, provided mailbox names which do not exist on the server would have been ignored silently. This fix will render the check UNKNOWN in case any non-existent names are encountered.

Change-Id: Iac930bca98da066b68626a4776dff9cefa5c487d