Revert "testlib: provide names for docker containers"
Reason: we get failures like:
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.43/containers/create?name=test-ubuntu-22.04-master-latest-b6b8a449a9-20240112090448: Conflict ("Conflict. The container name "/test-ubuntu-22.04-master-latest-b6b8a449a9-20240112090448" is already in use by container "cfb0f3123feb6ace8c89b4235237822c12845eb6503693030843173ef5cee4e9". You have to remove (or rename) that container to be able to reuse that name.")

This reverts commit 378905d48dda9987e9b28c9820a4b057c9a78399.

Change-Id: I79bc48edc0de8c68ce3f284c9689c8f7f8f8ef36