6458 FIX IPMI Management board: Use USER privilege level for monitoring
Previous versions used the ADMIN privilege level for monitoring via IPMI which
is way too much for this read-only access which is needed by Check_MK for
monitoring.

When you tried to use a non ADMIN privileged user before, an error like this occured:

ERROR: Requested privilege level is not allowed over this channel while
requesting privelege level 3 for [user]

You can now use less privileged users for monitoring.

FEED-931

Change-Id: I90e5edc5baee579ba287ab9bea51799e3658c305