Fix "cmk" command exception when invalid sub-options are given
When e.g. a valid mode "--list-hosts" is called with an invalid
sub option, for example "--hex", then an exception like this
could occur:

C+:
OMD[osim]:~$ cmk --debug --list-hosts --hex
Traceback (most recent call last):
  File "/omd/sites/osim/bin/cmk", line 89, in <module>
    exit_status = modes.call(o, a, opts, args)
  File "/omd/sites/osim/lib/python/cmk_base/modes/__init__.py", line 72, in call
    return mode.handler_function(*handler_args)
  File "/omd/sites/osim/lib/python/cmk_base/modes/check_mk.py", line 210, in mode_list_hosts
    hosts = _list_all_hosts(args, options)
  File "/omd/sites/osim/lib/python/cmk_base/modes/check_mk.py", line 227, in _list_all_hosts
    hostnames.update(config_cache.all_active_hosts())
  File "/omd/sites/osim/lib/python/cmk_base/config.py", line 2969, in all_active_hosts
    return self._all_active_hosts
AttributeError: 'CEEConfigCache' object has no attribute '_all_active_hosts'
C-:

This happened because Checkmk did not load the configuration before
executing the mode once an unknown option was in the command line.

Change-Id: I909e59318608589a5a3637f0cbd94e1393b01ce1