15354 FIX Remove "Encrypt notification daemon communication" check from "Analyze Configuration" in Checkmk Raw
"Encrypt notification daemon communication" is a Checkmk Enterprise feature,
so this check needs to be omitted in Checkmk Raw.

It previously failed with the following traceback:

```
error executing configuration test ACTestMknotifydCommunicationEncrypted
Traceback (most recent call last):
  File "/omd/sites/site/lib/python3/cmk/gui/watolib/analyze_configuration.py", line 157, in run
    results = list(self.execute())
              ^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/site/lib/python3/cmk/gui/wato/_ac_tests.py", line 527, in execute
    config = self._get_effective_global_setting("notification_spooler_config")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/site/lib/python3/cmk/gui/watolib/analyze_configuration.py", line 204, in _get_effective_global_setting
    return get_effective_global_setting(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/site/lib/python3/cmk/gui/watolib/sites.py", line 762, in get_effective_global_setting
    return default_values[varname]
           ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'notification_spooler_config'
```

CMK-21599

Change-Id: I359a94ac566c1361e5bfd66a5c31d88353222227