Revert "Bazelize Protobuf"
This reverts commit 15fd22faf4cf4e9a56ffe23f56f0afe12686335c.

Reason for revert:
packages/cmc/run --build-all failed because of 
ModuleNotFoundError: No module named 'pkg_resources'

Change-Id: Icc8a305a954749990888120900f523f556a5db90