13267 FIX AttributeError: 'Namespace' object has no attribute 'fetch_client_id' in check_mail and check_mail_loop
Trying to hide EWS related command line arguments from check_mail and check_mail_loop active checks
(which don't support EWS yet) led to exceptions being raised due to invalid access to now
non-existing arguments.
This change makes those arguments visible again with a hint about EWS not being available.

Change-Id: I51eb7c7c2294f882f076cfd670321ed59855b61a