omd config set RABBITMQ_PORT: fix invalid config
In case the chosen port was already occupied, the RABBITMQ_PORT was set
to "{port}\n{port}". This causes the `omd` tool to crash:
```
  File "/omd/versions/2.4.0-2024.12.31.cee/lib/python3/omdlib/config_hooks.py", line 275, in read_site_config
    var, value = line.split("=", 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```

CMK-20917

Change-Id: Ic12fa425659ab3c2c0b68fd19466180a293b834f