15556 FIX Jolokia JVM Memory Pools
Jolokia JVM Memory Pools may crash with the following traceback:
C+:
 File "/omd/sites/site_name/share/check_mk/checks/jolokia_jvm_memory", line 145, in check_jolokia_jvm_memory_pools
 value_max = usage.get("max", -1)
AttributeError: 'str' object has no attribute 'get'
C-:

This can be caused by an issue in the jolokia API and will result now in an UNKNOWN state.

SUP-13417

Change-Id: Ib6d41402b9c6c30b4db2adfb783627c4f5dc1a63