Fix `test_restore()` integration test
`test_restore()` would delete `main.mk` from the site but `cmk` cannot
run without it.  Instead, `cmk --restore` would fail with

    IOError: [Errno 2] No such file or directory [PATH TO main.mk]

leaving the test site broken.

This patch runs the test with `final.mk` instead of `main.mk`.

Change-Id: Ia581a9839765ff597c4ba1ee04c82e561798c2fb