Upgrade mod_wsgi from 4.9.4 to 5.0.2
Required for compilation problems in RHEL-10:

src/server/wsgi_interp.c:2223:17: error: implicit declaration of function ‘PySys_AddWarnOption’; did you mean ‘PySys_ResetWarnOptions’? [-Wimplicit-function-declaration]

Patch 0002-Migrate-from-distutils-to-setuptools-sysconfig.dif has been
upstreamed and is no longer needed.

Patch 0001-wsgi_fixVersionCheck.dif was required for SLES12SP0 which we
no longer support.

CMK-17203

Change-Id: I3bb05040b1d20435fadaa69b2376f67054d7c21f