17204 Fix sending notifications from Event Console
When trying to send a notification from the Event Console it failed because of a wrong RPATH in the rrdtool.
Affected systems include, but are not limited to, RHEL9 and derivates.

```
File "/omd/sites/SITE/lib/python3.12/importlib/init.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/omd/sites/SITE/lib/python3/cmk/base/modes/cee.py", line 16, in <module>
import rrdtool # type: ignore[import] # pylint: disable=import-error
^^^^^^^^^^^^^^
ImportError: librrd.so.8: cannot open shared object file: No such file or directory
```

SUP-19399 Event Console and Notifications

Change-Id: I236250f1f5ad9dc6d82795b5a7a4d8885892cb96