6517 FIX Nagios: Improved init script when tmpfs is not prepared
When using Nagios as core and executing "cmk -R" or "cmk -O"
on a totally stopped site ("omd stop" + "omd umount") without
previously executing "omd start" errors like this occured:

etc/init.d/nagios: line 72: /omd/sites/heute/tmp/nagios/nagios.cfg: No such file or directory
Nagios configuration file /omd/sites/heute/tmp/nagios/nagios.cfg not found. Terminating...

This has been replaced by a more helpful error message:

Change-Id: If442e8cdf01c752535daeaebc55a83e1438864df
ERROR: tmp directory is not ready. Use "omd start" to prepare it