Revert "CertificateSigningRequests in utils.crypto"
It may break integration tests with:
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /int_test/agent-receiver/registration_status/9f32a02a-7bca-4962-b133-79a65b73d61d (Caused by SSLError(SSLError(399, '[SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:3905)')))

This reverts commit 54fde3c70e8d286bf243e6ed380c2579d20dffeb.

Change-Id: Ib931e5be13d5fb18b6b71911d73d789d8b21bf89