3966 FIX apc_symmetra raritan_emx: Fixed wrong include "temperature.includes"
The checks were including non existant check include files which lead to an
error:

IOError: [Errno 2] No such file or directory: '/omd/sites/test/share/check_mk/checks/temperature.includes'

When using nagios core, this made the whole compilation of the configuration
fail in case the checks are used.