13442 FIX sap_hana_connect crashed on missing SERVERDB
sap_hana_connect crashed with

AttributeError ('NoneType' object has no attribute 'group')

when the connect string did not contain a SERVERDB entry.

SUP-12509

Change-Id: I7ebc613ed01f602333c1053cd9d4e8538ef050c4