prepare activating strictTemplates vueCompilerOptions (4/N)
the error message presented was on the callsite of CmkListAddButton:

src/components/CmkList/CmkList.vue(132,16): error TS2353:
    Object literal may only specify known properties, and
    'addElementLabel' does not exist in type 'Partial<{}> & Omit<{} &
    VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.

so it's not super obvious that this is the fix :-(

another fix would be to provide a single root element.

Change-Id: I4bfa66e30dab29788692fe880450e026960df2ce