Change mirror for Getopt-Long
the previous url is dead:
```
ERROR: no such package '@@Getopt-Long-2.43.tar.gz//file': java.io.IOException: Error downloading [https://archive.netbsd.org/pub/pkgsrc-archive/distfiles/2017Q3/Getopt-Long-2.43.tar.gz, https://artifacts.lan.tribe29.com/repository/upstream-archives/Getopt-Long-2.43.tar.gz] to /home/runner/.cache/bazel/_bazel_runner/aed53f964069daa6ab471b6b9883c077/external/Getopt-Long-2.43.tar.gz/file/downloaded: Connect timed out
```

Change-Id: I35ffd7bdfc1999cc8279c9da70b93f877ebe2405
(cherry picked from commit 470a9a25738ebed15c17977b5c2aeb55a6a88abe)