11756 FIX Fix errors after form submissions when using web server authentication
When using the web server level authentication (Basic, digest, kerberos, ...),
several form submissions raised an error like this: "AttributeError ('NoneType'
object has no attribute 'session_info')". This was caused by an incomplete session
initialization when using this kind of authentication.

Change-Id: I6c31cfcb8ce89e39768ca8d344550af4f9b1771e