#2826 FIX Disabled BI Aggregations no longer causing crashes when using "Precompile aggregations on demand"
This fixes the error <i>AttributeError: class DISABLED has no attribute 'lower'</i>, which is shown in
the BI sidebar snapin or written to the file <i>~/var/log/web.log</i>.
Because of this bug most of the aggregation views were empty.