13162 FIX check_mk_active: fix "AttributeError: 'NoneType' object has no attribute 'split'
This werk fixes the following issue with the check_mk_active:

- When the option warn/crit-age-oldest or warn/crit-age-newest was used the following error could occur:
  "AttributeError: 'NoneType' object has no attribute 'split'"

Change-Id: I721a5dcfbe4d325297189f8f1c3b53db308bd9fe