Global proxy: use SingleChoiceElementExtended for unique ID
To avoid errors like...
Exception: 'my-test-1' is not a valid, non-reserved Python identifier

I've updated

SingleChoiceElementExtended
SingleChoiceExtended

instead of

SingleChoiceElement
SingleChoice

CMK-28653

Change-Id: Ied24157c129430763fab53477364bdcbe0135e43