Revert "Add saas status menu item entry"
.. to fix
```
HtmlError: Found error: <div class="error">This page was not found. Sorry.</div
```
in GUI crawl tests

This reverts commit a99ee57ab4d14e59b8c22a04483f31c65dd868f1.

Change-Id: Ia587d4f4ac41a98d1dd2213a5813b2fc475247c4