6625 FIX Fixed possible failed mkbackup because of changed mknotifyd state file
The mknotifyd used specific names for a temporary file which was not excluded by
the mkbackup mechanism. When a backup was performed while the mknotifyd wrote it's
state file, the backup could fail with an exception like this:

OSError: [Errno 2] No such file or directory: \'/omd/sites/int_ma_5351/var/log/mknotifyd.state.new\'

CMK-1011

Change-Id: If50e8ba088197fbd027f8f57f786c6471f2cb811