Automation helper: Avoid integration test failures in CRE
```
AssertionError: FAILURE: Crash report detected! MKAutomationException:
Error running automation call <tt>restart</tt>, output: <pre>Error
precompiling checks for host aut-helper-test-host: Failed to lookup IPv4 address
of aut-helper-test-host via DNS: [Errno -2] Name or service not known
(["Cannot lookup IP address of 'aut-helper-test-host' (Failed to lookup IPv4
address of aut-helper-test-host via DNS: [Errno -2] Name or service not known).
The host will not be monitored correctly."],)
```

Change-Id: I69f9c465dbca808fba3f6a435bdab3c6396c70eb
(cherry picked from commit d3f6321e44e2510aa589683bf2bc3210dbba5fd7)