3969 FIX CentOS 5.5: Fixed incompatibility with the available OpenSSL 0.98
When opening the GUI, the following error occured, making the GUI unusable:

RuntimeError: You are linking against OpenSSL 0.9.8, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

This has been fixed now.