Revert "Reland "16251 Update monitoring-plugins to 2.4.0""
Still breaks builds...

  CCLD     check_nagios
/opt/bin/ld: /usr/lib64/libssl.so.3: undefined reference to `ossl_safe_getenv@OPENSSL_3.0.0'
collect2: error: ld returned 1 exit status

This reverts commit f01344c0447d0476b2c18d7ad09e7413274e2236.