Revert "16145 FIX "Always up" hosts can always notify"
It seems it breaks the integration tests with:
Exception: Did not find '] SERVICE NOTIFICATION: check-mk-notify;notify-test;Check_MK;CRITICAL;check-mk-notify;FAKE CRIT' in var/check_mk/core/history after 20 seconds
https://ci.lan.tribe29.com/job/checkmk/job/2.2.0/job/test-integration-single/1510/testReport/junit/pytest.tests.integration.notifications/test_simple_rbn/test_simple_rbn_service_notification/

This reverts commit 59ae761e146139ed09202292ebbcf66b4b953482.