Revert "Move CSE config to cmk/utils/cse"
It breaks github actions with:
tests/testlib/utils.py:402: error: Skipping analyzing "cmk.utils.cse.config": module is installed, but missing library stubs or py.typed marker  [import-untyped]

This reverts commit 69eb831645fc761f4a032e12c56b1c8adb5cb11d.