18054 FIX Ignore unknown "Disabled or enabled sections (SNMP)" during update config
If users had selected sections that have since been removed or are temporarily unavailable (due to disabled MKPs for instance), they would be prompted with a message like

```
WARNING: Invalid rule configuration detected
Ruleset: snmp_exclude_sections
Title: Disabled or enabled sections (SNMP)
Folder: main
Rule nr: 1
Exception: ... is not an allowed value
```

These invalid values are ignored now.
They do no harm and they are dropped upon editing the rule.

SUP-21764 CMK-20954

Change-Id: I39aa84aaa7bc72daa42066bcfdeb4bd1e135767d