Revert "update cryptography/pyopenssl"
This reverts commit 43af18d77e8b04c331abe49efa821d8503376867.

Try to fix:

```
  File "/usr/bin/omd", line 59, in <module>␛[0m
    import omdlib.main␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3/omdlib/main.py", line 54, in <module>␛[0m
    import omdlib.certs␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3/omdlib/certs.py", line 29, in <module>␛[0m
    from cmk.utils.certs import RootCA␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3/cmk/utils/certs.py", line 14, in <module>␛[0m
    from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey, RSAPublicKey␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3.11/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 11, in <module>␛[0m
    from cryptography.hazmat.primitives import _serialization, hashes␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3.11/site-packages/cryptography/hazmat/primitives/_serialization.py", line 11, in <module>␛[0m
    from cryptography.hazmat.primitives.hashes import HashAlgorithm␛[0m
  File "/omd/versions/2023.10.04.cee/lib/python3.11/site-packages/cryptography/hazmat/primitives/hashes.py", line 10, in <module>␛[0m
    from cryptography.hazmat.bindings._rust import openssl as rust_openssl␛[0m
ImportError: /omd/versions/2023.10.04.cee/lib/python3.11/site-packages/cryptography/hazmat/bindings/_rust.abi3.so: undefined symbol: EVP_default_properties_is_fips_enabled␛[0m
```