17044 FIX gcp_status: Fix KeyError: me-central1
This change affects users which have configured the rule 'Google Cloud Platform (GCP) Status'.
Previously, Checkmk did not handle incidents correctly, which had set `me-central1` as an associated location.
This was the corresponding traceback:
```
  File "/omd/sites/mon_home/lib/python3/cmk/plugins/gcp/agent_based/gcp_status.py", line 72, in parse
    data.setdefault(constants.RegionMap[location.id_], []).append(incident)
KeyError: 'me-central1'
```
With this werk, the crash is fixed.

*Updated the Region Mapping based on this link - https://github.com/GoogleCloudPlatform/gcping/blob/main/tools/terraform/regions.json
*Multiple regions have been added - 'africa-south1', 'europe-west10', 'europe-west12', 'me-central1', 'me-central2'

CMK-21087

Change-Id: Ie2a0ca7d249f6c1add07043550cc301bcba5c1da