When monitoring clustered hosts using Nagios as core, the Check_MK service always resulted in an UNKNOWN state and this exception:
NameError: global name 'set_use_cachefile' is not defined

Conflicts:
	ChangeLog
	modules/check_mk.py