Revert "17214 FIX Automatic Disk Cleanup: Allow Site Specific Configuration"
This reverts commit b5e7ac021fec05c976799030dfc31bc72aab88a0.

Breaks system level tests with an AttributeError. Extract from a crash
report:

```
        [
            "\/omd\/sites\/int_test\/lib\/python3\/cmk\/gui\/wato\/_omd_configuration.py",
            254,
            "default_globals",
            "return {\"diskspace_cleanup\": diskspace.config.DEFAULT_CONFIG.model_dump(exclude_none=True)}"
        ]
    ],
    "exc_type": "AttributeError",
    "exc_value": "module 'cmk.diskspace' has no attribute 'config'",
```