Disable slack build failure notification
Disabled for the moment. It currently does not work because of some
wrong configuration.

From the build logs:

[Pipeline] slackSend
Slack Send Pipeline step running, values are - baseUrl: <empty>,
teamDomain: <empty>, channel: build-notifications, color: danger,
botUser: true, tokenCredentialId: <empty>, iconEmoji <empty>, username
<empty>
ERROR: Slack notification failed with exception:
java.lang.IllegalArgumentException: the token with the provided ID could
not be found and no token was specified

Change-Id: Iffddaec4edd5bd6bf3ed95c8c0bd1be59859d851