Fix up after 9de2c014a0
* aboves commit removed the following line:
```
	mkdir -p $(DESTDIR)$(OMD_BASE)/sites
	mkdir -p $(DESTDIR)$(OMD_BASE)/apache
```
* under sles/almalinux, `/opt/omd/apache` was not created anymore after the omd installation
* so it would fail during site creation with:
```
  File "/omd/versions/2.5.0-2025.12.19.ultimatemt/lib/python3/omdlib/system_apache.py", line 98, in create_apache_hook
    with open(apache_config, "w") as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/omd/apache/int_test.conf'
```

As this is now handled at a more central place, we should not get any distro specific failures anymore

Change-Id: I33441f9a3fc38c85bb29a3620f51760289367f06