15099 FIX crash when calling bulk-delete via the REST API
Previously, when doing a bulk_delete operation via the REST API,
an exception could occur under certain conditions:

If the error occured, in the logs these lines are occuring.

  PermissionError: Required permissions not declared for this endpoint.
  Endpoint: <Endpoint cmk.gui.plugins.openapi.endpoints.host_config:bulk_delete>
  Permission: general.see_all
  Used permission: {'wato.all_folders', 'general.see_all', 'wato.manage_hosts'}
  Declared: AllPerm([{wato.manage_hosts}, {wato.all_folders}?)

This werk fixes this problem.

For 2.2: Also backport permission changes from master.

Change-Id: I2b712fc7f96645e53d8045472544ab097ee0db24