omd update: fix `[Errno 39]: ... /etc/jaeger'
Regression caused by the change with Change-Id:
I1dfd92e20ab1065b0d4b957a00b66e05cb0ac8e4

```
  File "/omd/versions/2.4.0-2024.12.17.cce/lib/python3.12/pathlib.py", line 1351, in rmdir
    os.rmdir(self)
OSError: [Errno 39] Directory not empty: '/omd/sites/atlanta/etc/jaeger'
```

CMK-20846

Change-Id: I872e30da685fecbad2e05bea495288d39ca25bf8