omd: Fix `omd init`
Previously, this command would always terminate with

```
  File
"/omd/versions/2.5.0-2026.02.04.ultimate/lib/python3/omdlib/main.py",
line 1973, in init_site
    os.symlink("version/" + d, site_home + "/" + d)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileExistsError: [Errno 17] File exists: 'version/bin' ->
'/omd/sites/test_site/bin'
```

This a regression introduced in the change with ID:
I4614f887b7256924322fd6396385bfbbdfa43bc0

CMK-29980

Change-Id: I0e9379d0e7dd2f99089183ed990e9f3def22db93
(cherry picked from commit fa477f1fa613e9a7cc3b4acc5ddc10afe274993f)