16414 FIX Support Old Configuration Format For 'Disable notifications'
In Werk #6417, we announced that some changes to `etc/check_mk/conf.d/wato/contacts.mk` are
necessary before updating. In case a user did not migrate his configuration, they would encounter
the following crash in 2.2.0, but not in 2.1.0:
```
  File "/omd/sites/edding/lib/python3/cmk/base/notify.py", line 968, in rbn_rule_contacts
    if disable_notifications_opts.get("disable", False):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
```
This crash is now no longer shown.

Change-Id: I8f1a0c0de4fb73eab6c8b69224a60fcfa70b03ea