Fix for bazel build errors for //cmk/lib_cmk_cee, etc
Was previous trying to use tar files as inputs to python libraries.

Now dependencies are maintained as a separate list as is done in the
master branch.

    ERROR: Fetching some target dependencies failed with errors: Analysis of target '//cmk:cmk_cce' failed;
    build aborted: in deps attribute of py_library rule //cmk:lib_cmk_cce: '//non-free/packages/cmk-mknotifyd:cmk_mknotifyd_pkg'
    does not have mandatory providers: 'PyInfo' or 'PyVirtualInfo'

Change-Id: Ie02dae3c4dd14382e51a409e9707665020a95aef