Automation helpers: Don't watch plugins and only load plugins once at startup
The current plugin loading mechanism does not support reloads in certain
scenarios. For example:

```
OMD[heute]:~$ python3
Python 3.12.3 (main, Dec  3 2024, 19:13:31) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from importlib import import_module, reload
>>> import sys
>>> from pathlib import Path
>>>
>>> import_module("cmk.plugins.collection.agent_based.uptime")
<module 'cmk.plugins.collection.agent_based.uptime' from '/omd/sites/heute/lib/python3/cmk/plugins/collection/agent_based/uptime.py'>
>>> Path("local/lib/check_mk/plugins/collection").exists()
False
>>> Path("local/lib/check_mk/plugins/collection/agent_based").mkdir(parents=True)
>>> Path("local/lib/check_mk/plugins/collection/agent_based/uptime2.py").write_text(Path("lib/check_mk/plugins/collection/agent_based/uptime.py").read_text())
4762
>>> import_module("cmk.plugins.collection.agent_based.uptime2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/omd/sites/heute/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cmk.plugins.collection.agent_based.uptime2'
>>> reload(sys.modules["cmk.plugins.collection"])
<module 'cmk.plugins.collection' (namespace) from ['/omd/sites/heute/local/lib/python3/cmk/plugins/collection', '/omd/sites/heute/lib/python3/cmk/plugins/collection']>
>>> import_module("cmk.plugins.collection.agent_based.uptime2")
<module 'cmk.plugins.collection.agent_based.uptime2' from '/omd/sites/heute/local/lib/python3/cmk/plugins/collection/agent_based/uptime2.py'>
>>>
```

While this could be fixed, we don't actually need to support modifying plugins
without restarting the site at the moment. Therefore, not watching and reloading
the plugins is currently the fastest way forward.

Change-Id: Id285026fbbbb8be3be829b8d06c89858a85f2d6c