Revert "unit resilience test: Store & archive junit report"
This reverts commit c1bc36cc1ae9b060f00876844f3d97834e9f27cc.
It breaks the resilience job:
hudson.remoting.ProxyException: groovy.lang.MissingPropertyException: No such property: name for class: Script6
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.getProperty(DefaultInvoker.java:39)
	at com.cloudbees.groovy.cps.impl.PropertyAccessBlock.rawGet(PropertyAccessBlock.java:20)
	at Script6.main(Script6.groovy:24) <--- look here