7332 FIX Backup/Restore: Fixed incomplete #7224
The fix #7224 which was part of 1.5.0p13 did not really fix the problem with
vanishing files during the backup. It caught the problematic situation but
lead to another exception (AttributeError: 'BackupTarFile' object has no attribute '_verbose').

Change-Id: Ibed9fa2f7eeb3bd6b10cafe6fb75f042c7f4a564