gcp_cost: fix migration to ignore predictive levels
previously the following exception was shown during update:

    Exception: Could not migrate {'__injected__': None, 'period': 'wday', 'horizon': 90, 'levels_upper': ('absolute', (0.0, 0.0))} to SimpleLevelsConfigModel. Consider using Levels instead of SimpleLevels.

CMK-20528

Change-Id: Ieae949be15d24c3de272ea674c44cd9fb83019a7