Revert "Make windows integration tests independent of top level pytest config"
It breaks winagt-build-modules:
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
make: *** [Makefile:117: venv] Error 111:21:28      match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
make: *** [Makefile:117: venv] Error 1

This reverts commit 74fd95b3e30b6d7601123d60e24e99eb634a481d.