11873 FIX Fix exception caused by custom host attributes when saving host changes
When some kind of custom host attribute has been defined and is used in the host
configuration, this may lead to an exception like this when editing or deleting
hosts: <tt>Exception: AttributeError ('HostAttributeMYATTRIBUTEConcrete' object has no attribute 'is_explicit')</tt>.

Besides the fix, this change also adds the type hints that were missing
to uncover this issue.

Change-Id: I87921cf46f82ca44b525c5ce64240f063f45279d