Revert "Remove dead code"
This reverts commit 646f14fcfd1bfb349dd8ecb2db0f321e00557c70.

Reason for revert:
```
FileNotFoundError: [Errno 2] No such file or directory: '/omd/sites/int_test/share/check_mk/agents/linux/cmk-agent-ctl'
```

Change-Id: I79b42e712fa3f0316b88065392b84330409deca9