werk: improve error reporting
show message from git on error instead of traceback

for example

```
% werk pick 79969
error: short object ID 79969 is ambiguous
hint: The candidates are:
hint:   073ef8319e0 commit 2022-01-19 - Update notes for submitted changes
hint:   f8119ff7b79 commit 2024-06-13 - 16512 FIX Restart scheduler after setting "use the
status of a service"
hint:   d3b3b7c2538 tree
hint:   799697847c0 blob
hint:   79969e8229f blob
fatal: ambiguous argument '79969': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

was
```
Traceback (most recent call last):
  File "/home/mlaurin/src/check_mk-230.git/packages/cmk-werks/cmk/werks/cli.py", line 884,
in werk_cherry_pick
    result = subprocess.run(
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'diff-tree', '--no-commit-id', '--name-only
', '-r', '79969']' returned non-zero exit status 128.
```

Change-Id: I539641261ad0f7764cebc31376fcd515477fc607