19071 FIX Fixed bug in --nagios-config
Previously, running `cmk --nagios-config` or `cmk -N` could fail with the
following error:

   TypeError: OnPremLicensingHandler.__init__() missing 1 required positional argument: 'state_handler'

This bug has been fixed, and the commands above should now run successfully.

CMK-35097

Change-Id: I041661f7146d43894020d1d92bd84b076a6a6964