Host label sync: Improve log entry in case remote site is not reachable
Align the error message with the one from the audit log and changes sync
jobs. Do not log a traceback anymore.

```
2025-01-13 16:21:39,426 [40] [cmk.web 299933] Failed to get audit logs and site changes from site heute_remote_1: Site is not running
2025-01-13 16:21:39,434 [40] [cmk.web 299933] Failed to get audit logs and site changes from site heute_remote_2: Site is not running
2025-01-13 16:21:39,435 [40] [cmk.web 299933] Failed to get changes from sites: heute_remote_1, heute_remote_2.
2025-01-13 16:21:39,626 [40] [cmk.web 299933] Exception (heute_remote_2, discovered_host_label_sync)
Traceback (most recent call last):
  File "/omd/sites/heute/lib/python3/cmk/gui/watolib/host_label_sync.py", line 212, in _execute_site_sync
    raw_result = do_remote_automation(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/heute/lib/python3/cmk/gui/watolib/automations.py", line 358, in do_remote_automation
    serialized_response = _do_remote_automation_serialized(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/heute/lib/python3/cmk/gui/watolib/automations.py", line 296, in _do_remote_automation_serialized
    response = get_url(
               ^^^^^^^^
  File "/omd/sites/heute/lib/python3/cmk/gui/watolib/automations.py", line 530, in get_url
    return get_url_raw(url, insecure, auth, data, files, timeout).text
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/heute/lib/python3/cmk/gui/watolib/automations.py", line 413, in get_url_raw
    raise MKUserError(None, _("Site is not running"))
cmk.gui.exceptions.MKUserError: Site is not running
```

Change-Id: Ie83c5d34e612008496b966b49f5c0da88b7ede2d