Remove `OTEL_EXPORTER_OTLP_ENDPOINT` env. var. from dockerized test runs
Get rid of
```
'OTEL_EXPORTER_OTLP_ENDPOINT': ''
```
in CI system test executions, since this leads to
```
18:50:24.693 ERROR Failed to export traces to , error code: StatusCode.UNKNOWN
Traceback (most recent call last):
  File "/git/.venv/lib/python3.12/site-packages/opentelemetry/exporter/otlp/proto/grpc/exporter.py", line 299, in _export
    self._client.Export(
  File "/git/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1181, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/git/.venv/lib/python3.12/site-packages/grpc/_channel.py", line 1006, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Failed to create client channel"
	debug_error_string = "UNKNOWN:Failed to create client channel {grpc_status:2}"
```
The tests don't fail, but the logs are bloated by this.

CMK-22574

Change-Id: I32b8c1ebe7858b4060de2a40e8123d725e8422ca