Fix reportlab: PIL usage
* we need to bump reportlab to 3.5.18 which includes:
https://hg.reportlab.com/hg-public/reportlab/rev/37fce4b8f084
* otherwise reportlab will not work with Pillow in version 6.2.2 and
crash with:
AttributeError ('module' object has no attribute 'VERSION'

Change-Id: I83a93a6d29e57b61b14c37276293f0e82e936d6f