Fix NameError in automation helper when activating relay changes
The following error appears when activating changes in the relays
config file:

```
2025-09-04 16:40:13,057 [40] [791670] Traceback (most recent call last):
  File "/omd/sites/v250/lib/python3/cmk/base/config.py", line 804, in _load_config
    _load_config_file(path, global_dict)
  File "/omd/sites/v250/lib/python3/cmk/base/config.py", line 759, in _load_config_file
    exec(compile(file_to_load.read_text(), file_to_load, "exec"), into_dict, into_dict)  # nosec B102 # BNS:aee528
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/omd/sites/v250/etc/check_mk/conf.d/wato/relay.mk", line 3, in <module>
    relays.update({'24407e7b-eb13-40a9-814b-a7d1c5ac37a3': {'alias': 'Munich 1', 'siteid': 'v250'}, 'cbdbacbf-8360-44c1-9a23-4e03b50a86b7': {'alias': 'host1 relay', 'siteid': 'v250'}})
    ^^^^^^
NameError: name 'relays' is not defined
```

Fix it by providing a default value as it expects

Change-Id: Ia57380212df3ceced766a2e2503923dc4b536a33